### ISSUE TITLE
derivative work of boost.fiber

### ISSUE THREAD

**Issue by olk** [romange/helio#194]
I think helio is derivative work of boost.fiber.
Your implementation resembles a lot of boost.fiber - for instance the use of linked lists or the idea of a dispatching-fiber inside the scheduler or the kind of queues to handle sleeping/blocked/remote fibers.
You have removed all references to the original work of boost.fiber - including the license - and claims that all of this code is only a result of you thoughts - that is really is annoying and a slap int the face of the authors of boost.fiber.

**Comment by romange** [comment]
Hi Oliver, 
First of all that was not my intent at all. Helio was based on Boost.Fibers up until May this year, you can still see BoostFibers tag here: https://github.com/romange/helio/releases/tag/BoostFibers

Due to some technical limitations of how I wanted to integrate Fibers library with iouring polling code I had to fork the fibers code. 
I am totally open and transaparent about the fact that all fiber related code is largely influenced by your design. I think your Boost.Fibers library is fantastic. In fact you can find my modest contributions to your project over the past years.

Please tell me how I can fix this and what kind of desclaimer/licence addendum you want me to put and I would gladly do that. 
Again, it was not my intent to slap anyone :) and I bring you my sincere apologies regarding the whole thing.

**Comment by olk** [comment]
Hello Roman,
unfortunately I was not able to find your email ... that's why I used this way.
I'm fine if you could set a disclaimer that mentions/links to boost.fiber.

I'm a little picky because I noticed that in the past some people have copied the boost code and replaced the authors names by their own and promoted the (unmodified) code it as their own work ... unfair practice.
